[package]
name = "http-serve"
version = "0.2.0-alpha"
authors = ["Scott Lamb <slamb@slamb.org>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "Conditional GET, HEAD, and byte range serving for abstract HTTP entities."
keywords = ["http", "file", "range"]
categories = ["web-programming::http-server"]
repository = "https://github.com/scottlamb/http-serve"
edition = "2018"

[badges]
travis-ci = { repository = "scottlamb/http-serve" }

[dependencies]
bytes = "0.4.8"
flate2 = "1.0.1"
futures = "0.1.21"
http = "0.1.5"
httpdate = "0.3.2"
hyper = "0.12.0"
mime = "0.3.7"
smallvec = "0.6.1"
time = "0.1.40"
tokio-threadpool = "0.1.3"
unicase = "2.1.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.6", features = ["std", "winbase"] }

[dev-dependencies]
criterion = "0.2"
env_logger = "0.6.2"
lazy_static = "1.0.1"
leak = "0.1.2"
log = "0.4.1"
reqwest = "0.9.4"
tempfile = "3.1.0"
tokio = "0.1.6"

[profile.release]
debug = true

[[bench]]
name = "file"
harness = false

[[bench]]
name = "inmem"
harness = false
