[package]
name = "http-entity"
version = "0.0.1"
authors = ["Scott Lamb <slamb@slamb.org>"]
license = "MIT"

[dependencies]
futures = "0.1.7"
hyper = { git = "https://github.com/hyperium/hyper" }
mime = "0.3"
smallvec = "0.4"
time = "0.1"

[dev-dependencies]
env_logger = "0.4"
futures-cpupool = "0.1"
http-file = { path = "./http-file" }
lazy_static = "0.2"
log = "0.3"
reqwest = "0.6.0"

#[workspace]
#members = ["http-file"]

[profile.release]
debug = true
