[package]
name = "http-entity"
version = "0.0.1"
authors = ["Scott Lamb <slamb@slamb.org>"]
license = "MIT"

[dependencies]
futures = "0.1.7"
hyper = { git = "https://github.com/hyperium/hyper" }
mime = "0.2"
smallvec = "0.3"
time = "0.1"
tokio-core = "0.1"

[dev-dependencies]
env_logger = "0.4"
lazy_static = "0.2"
log = "0.3"
reqwest = "0.3.0"
