[package]
name = "http-entity"
version = "0.0.1"
authors = ["Scott Lamb <slamb@slamb.org>"]
license = "MIT"

[dependencies]
futures = "0.1.7"
hyper = "0.11"
mime = "0.3"
smallvec = "0.6"
time = "0.1"

[dev-dependencies]
env_logger = "0.4"
futures-cpupool = "0.1"
http-file = { path = "./http-file" }
lazy_static = "1.0"
log = "0.4"
reqwest = "0.8"

#[workspace]
#members = ["http-file"]

[profile.release]
debug = true
