[package]
name = "http-serve"
version = "0.2.0-alpha"
authors = ["Scott Lamb <slamb@slamb.org>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "Conditional GET, HEAD, and byte range serving for abstract HTTP entities."
keywords = ["http", "file", "range"]
categories = ["web-programming::http-server"]
repository = "https://github.com/scottlamb/http-serve"
edition = "2018"

[badges]
travis-ci = { repository = "scottlamb/http-serve" }

[dependencies]
bytes = "0.5.3"
flate2 = "1.0.1"
futures = "0.3.1"
http = "0.2.0"
http-body = "0.3.1"
httpdate = "0.3.2"
hyper = "0.13.0"
mime = "0.3.7"
smallvec = "1.0.0"
socket2 = { version = "0.3.10", features = ["reuseport"] }
time = "0.1.40"
tokio = { version = "0.2.4", features = ["blocking", "macros", "rt-threaded"] }
unicase = "2.1.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.6", features = ["std", "winbase"] }

[dev-dependencies]
criterion = "0.3"
env_logger = "0.7.1"
httparse = "1.3.4"
lazy_static = "1.0.1"
log = "0.4.1"
reqwest = "0.9.4"
tempfile = "3.1.0"

[profile.release]
debug = true

[profile.bench]
debug = true

[[bench]]
name = "file"
harness = false

[[bench]]
name = "inmem"
harness = false
